default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: interview-project_development
  host: 0.0.0.0
  port: 5434
  user: interview-project_development
  password: interview-project_development

test:
  <<: *default
  database: interview-project_test
  host: 0.0.0.0
  port: 5433
  user: interview-project_test
  password: interview-project_test

production:
  <<: *default
  database: interview-project_production
  username: interview-project
  password: <%= ENV['INTERVIEW-PROJECT_DATABASE_PASSWORD'] %>
