test:
  url: test
  port: 6379

development:
  url: localhost
  port: 6379

staging:
  url: <%= ENV['REDIS_ADDR'] %>
  port: <%= ENV['REDIS_PORT'] || '6379' %>

migration:
  url: <%= ENV['REDIS_ADDR']%>
  port: <%= ENV['REDIS_PORT'] || '6379' %>

production:
  url: <%= ENV['REDIS_ADDR'] %>
  port: <%= ENV['REDIS_PORT'] || '6379' %>
